-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.asignaciones
(
    id bigserial NOT NULL,
    user_id bigint NOT NULL,
    municipio_id bigint NOT NULL,
    fecha_asignacion date NOT NULL,
    fecha_cese date,
    estado character varying(255) COLLATE pg_catalog."default" NOT NULL DEFAULT 'Activo'::character varying,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    CONSTRAINT asignaciones_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.audits
(
    id bigserial NOT NULL,
    user_type character varying(255) COLLATE pg_catalog."default",
    user_id bigint,
    event character varying(255) COLLATE pg_catalog."default" NOT NULL,
    auditable_type character varying(255) COLLATE pg_catalog."default" NOT NULL,
    auditable_id bigint NOT NULL,
    old_values text COLLATE pg_catalog."default",
    new_values text COLLATE pg_catalog."default",
    url text COLLATE pg_catalog."default",
    ip_address inet,
    user_agent character varying(1023) COLLATE pg_catalog."default",
    tags character varying(255) COLLATE pg_catalog."default",
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    CONSTRAINT audits_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.cache
(
    key character varying(255) COLLATE pg_catalog."default" NOT NULL,
    value text COLLATE pg_catalog."default" NOT NULL,
    expiration integer NOT NULL,
    CONSTRAINT cache_pkey PRIMARY KEY (key)
);

CREATE TABLE IF NOT EXISTS public.cache_locks
(
    key character varying(255) COLLATE pg_catalog."default" NOT NULL,
    owner character varying(255) COLLATE pg_catalog."default" NOT NULL,
    expiration integer NOT NULL,
    CONSTRAINT cache_locks_pkey PRIMARY KEY (key)
);

CREATE TABLE IF NOT EXISTS public.centro_poblados
(
    id bigserial NOT NULL,
    nombre character varying(255) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    deleted_at timestamp(0) without time zone,
    CONSTRAINT centro_poblados_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.documento_estados
(
    id bigserial NOT NULL,
    nombre character varying(50) COLLATE pg_catalog."default" NOT NULL,
    color_ui character varying(7) COLLATE pg_catalog."default",
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    CONSTRAINT documento_estados_pkey PRIMARY KEY (id),
    CONSTRAINT documento_estados_nombre_unique UNIQUE (nombre)
);

CREATE TABLE IF NOT EXISTS public.eje_via
(
    gid serial NOT NULL,
    fid_polyli double precision,
    exty numeric,
    nombre_via character varying(50) COLLATE pg_catalog."default",
    geom geometry(MultiLineString,32719),
    CONSTRAINT eje_via_pkey PRIMARY KEY (gid)
);

CREATE TABLE IF NOT EXISTS public.failed_jobs
(
    id bigserial NOT NULL,
    uuid character varying(255) COLLATE pg_catalog."default" NOT NULL,
    connection text COLLATE pg_catalog."default" NOT NULL,
    queue text COLLATE pg_catalog."default" NOT NULL,
    payload text COLLATE pg_catalog."default" NOT NULL,
    exception text COLLATE pg_catalog."default" NOT NULL,
    failed_at timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT failed_jobs_pkey PRIMARY KEY (id),
    CONSTRAINT failed_jobs_uuid_unique UNIQUE (uuid)
);

CREATE TABLE IF NOT EXISTS public.job_batches
(
    id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    total_jobs integer NOT NULL,
    pending_jobs integer NOT NULL,
    failed_jobs integer NOT NULL,
    failed_job_ids text COLLATE pg_catalog."default" NOT NULL,
    options text COLLATE pg_catalog."default",
    cancelled_at integer,
    created_at integer NOT NULL,
    finished_at integer,
    CONSTRAINT job_batches_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.jobs
(
    id bigserial NOT NULL,
    queue character varying(255) COLLATE pg_catalog."default" NOT NULL,
    payload text COLLATE pg_catalog."default" NOT NULL,
    attempts smallint NOT NULL,
    reserved_at integer,
    available_at integer NOT NULL,
    created_at integer NOT NULL,
    CONSTRAINT jobs_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.materiales_via
(
    id bigserial NOT NULL,
    nombre character varying(255) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    CONSTRAINT materiales_via_pkey PRIMARY KEY (id),
    CONSTRAINT materiales_via_nombre_unique UNIQUE (nombre)
);

CREATE TABLE IF NOT EXISTS public.migrations
(
    id serial NOT NULL,
    migration character varying(255) COLLATE pg_catalog."default" NOT NULL,
    batch integer NOT NULL,
    CONSTRAINT migrations_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.model_has_permissions
(
    permission_id bigint NOT NULL,
    model_type character varying(255) COLLATE pg_catalog."default" NOT NULL,
    model_id bigint NOT NULL,
    CONSTRAINT model_has_permissions_pkey PRIMARY KEY (permission_id, model_id, model_type)
);

CREATE TABLE IF NOT EXISTS public.model_has_roles
(
    role_id bigint NOT NULL,
    model_type character varying(255) COLLATE pg_catalog."default" NOT NULL,
    model_id bigint NOT NULL,
    CONSTRAINT model_has_roles_pkey PRIMARY KEY (role_id, model_id, model_type)
);

CREATE TABLE IF NOT EXISTS public.municipios
(
    id bigserial NOT NULL,
    nombre character varying(255) COLLATE pg_catalog."default" NOT NULL,
    departamento character varying(255) COLLATE pg_catalog."default" NOT NULL,
    logo text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    CONSTRAINT municipios_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.password_reset_tokens
(
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    token character varying(255) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp(0) without time zone,
    CONSTRAINT password_reset_tokens_pkey PRIMARY KEY (email)
);

CREATE TABLE IF NOT EXISTS public.permissions
(
    id bigserial NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    guard_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    CONSTRAINT permissions_pkey PRIMARY KEY (id),
    CONSTRAINT permissions_name_guard_name_unique UNIQUE (name, guard_name)
);

CREATE TABLE IF NOT EXISTS public.personal_access_tokens
(
    id bigserial NOT NULL,
    tokenable_type character varying(255) COLLATE pg_catalog."default" NOT NULL,
    tokenable_id bigint NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    token character varying(64) COLLATE pg_catalog."default" NOT NULL,
    abilities text COLLATE pg_catalog."default",
    last_used_at timestamp(0) without time zone,
    expires_at timestamp(0) without time zone,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    CONSTRAINT personal_access_tokens_pkey PRIMARY KEY (id),
    CONSTRAINT personal_access_tokens_token_unique UNIQUE (token)
);

CREATE TABLE IF NOT EXISTS public.personas
(
    id bigserial NOT NULL,
    nombre character varying(255) COLLATE pg_catalog."default" NOT NULL,
    primer_apellido character varying(255) COLLATE pg_catalog."default" NOT NULL,
    segundo_apellido character varying(255) COLLATE pg_catalog."default",
    carnet character varying(255) COLLATE pg_catalog."default" NOT NULL,
    expedido character varying(5) COLLATE pg_catalog."default",
    telefono character varying(255) COLLATE pg_catalog."default",
    fecha_nacimiento date,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    ci_fecha_caducidad date,
    ci_es_indefinido boolean NOT NULL DEFAULT false,
    CONSTRAINT personas_pkey PRIMARY KEY (id),
    CONSTRAINT personas_carnet_unique UNIQUE (carnet)
);

CREATE TABLE IF NOT EXISTS public.planimetrias
(
    id bigserial NOT NULL,
    codigo character varying(255) COLLATE pg_catalog."default" NOT NULL,
    fecha_aprobacion date,
    documento_aprobacion character varying(255) COLLATE pg_catalog."default",
    municipio_id bigint NOT NULL,
    limite_geografico geometry(Polygon,4326) NOT NULL,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    deleted_at timestamp(0) without time zone,
    centro_poblado character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT planimetrias_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.poligono_uno
(
    gid integer,
    codigo character varying(10) COLLATE pg_catalog."default",
    cod numeric,
    codigo_1 numeric,
    mz numeric,
    pred numeric,
    prop_1 character varying(254) COLLATE pg_catalog."default",
    ci_1 character varying(254) COLLATE pg_catalog."default",
    prop_2 character varying(254) COLLATE pg_catalog."default",
    ci_2 character varying(254) COLLATE pg_catalog."default",
    prop_3 character varying(254) COLLATE pg_catalog."default",
    ci_3 character varying(254) COLLATE pg_catalog."default",
    prop_4 character varying(254) COLLATE pg_catalog."default",
    ci_4 character varying(254) COLLATE pg_catalog."default",
    prop_5 character varying(254) COLLATE pg_catalog."default",
    ci_5 character varying(254) COLLATE pg_catalog."default",
    prop_6 character varying(254) COLLATE pg_catalog."default",
    ci_6 character varying(254) COLLATE pg_catalog."default",
    prop_7 character varying(254) COLLATE pg_catalog."default",
    ci_7 character varying(254) COLLATE pg_catalog."default",
    prop character varying(254) COLLATE pg_catalog."default",
    ci_8 character varying(254) COLLATE pg_catalog."default",
    norte character varying(254) COLLATE pg_catalog."default",
    sur character varying(254) COLLATE pg_catalog."default",
    este character varying(254) COLLATE pg_catalog."default",
    norte1 character varying(254) COLLATE pg_catalog."default",
    area_legal numeric,
    vinculo numeric,
    p_1 character varying(254) COLLATE pg_catalog."default",
    p_2 character varying(254) COLLATE pg_catalog."default",
    p_3 character varying(254) COLLATE pg_catalog."default",
    p_4 character varying(254) COLLATE pg_catalog."default",
    p_5 character varying(254) COLLATE pg_catalog."default",
    p_6 character varying(254) COLLATE pg_catalog."default",
    p_7 character varying(254) COLLATE pg_catalog."default",
    p_8 character varying(254) COLLATE pg_catalog."default",
    sup numeric,
    mat_via character varying(15) COLLATE pg_catalog."default",
    mv_tierra character varying(15) COLLATE pg_catalog."default",
    mv_adoquin character varying(10) COLLATE pg_catalog."default",
    agua character varying(10) COLLATE pg_catalog."default",
    elec character varying(5) COLLATE pg_catalog."default",
    alc character varying(5) COLLATE pg_catalog."default",
    obs_ character varying(50) COLLATE pg_catalog."default",
    cod_n character varying(10) COLLATE pg_catalog."default",
    no_pl_gam character varying(12) COLLATE pg_catalog."default",
    no_matrc character varying(30) COLLATE pg_catalog."default",
    area_folio character varying(15) COLLATE pg_catalog."default",
    geom geometry(MultiPolygonZM,32719),
    via_id integer
);

CREATE TABLE IF NOT EXISTS public.poligonos
(
    gid serial NOT NULL,
    codigo character varying(10) COLLATE pg_catalog."default",
    cod numeric,
    codigo_1 numeric,
    nombre_via character varying(254) COLLATE pg_catalog."default",
    mz numeric,
    pred numeric,
    prop_1 character varying(254) COLLATE pg_catalog."default",
    ci_1 character varying(254) COLLATE pg_catalog."default",
    prop_2 character varying(254) COLLATE pg_catalog."default",
    ci_2 character varying(254) COLLATE pg_catalog."default",
    prop_3 character varying(254) COLLATE pg_catalog."default",
    ci_3 character varying(254) COLLATE pg_catalog."default",
    prop_4 character varying(254) COLLATE pg_catalog."default",
    ci_4 character varying(254) COLLATE pg_catalog."default",
    prop_5 character varying(254) COLLATE pg_catalog."default",
    ci_5 character varying(254) COLLATE pg_catalog."default",
    prop_6 character varying(254) COLLATE pg_catalog."default",
    ci_6 character varying(254) COLLATE pg_catalog."default",
    prop_7 character varying(254) COLLATE pg_catalog."default",
    ci_7 character varying(254) COLLATE pg_catalog."default",
    prop character varying(254) COLLATE pg_catalog."default",
    ci_8 character varying(254) COLLATE pg_catalog."default",
    norte character varying(254) COLLATE pg_catalog."default",
    sur character varying(254) COLLATE pg_catalog."default",
    este character varying(254) COLLATE pg_catalog."default",
    norte1 character varying(254) COLLATE pg_catalog."default",
    area_legal numeric,
    vinculo numeric,
    p_1 character varying(254) COLLATE pg_catalog."default",
    p_2 character varying(254) COLLATE pg_catalog."default",
    p_3 character varying(254) COLLATE pg_catalog."default",
    p_4 character varying(254) COLLATE pg_catalog."default",
    p_5 character varying(254) COLLATE pg_catalog."default",
    p_6 character varying(254) COLLATE pg_catalog."default",
    p_7 character varying(254) COLLATE pg_catalog."default",
    p_8 character varying(254) COLLATE pg_catalog."default",
    sup numeric,
    mat_via character varying(15) COLLATE pg_catalog."default",
    mv_tierra character varying(15) COLLATE pg_catalog."default",
    mv_adoquin character varying(10) COLLATE pg_catalog."default",
    agua character varying(10) COLLATE pg_catalog."default",
    elec character varying(5) COLLATE pg_catalog."default",
    alc character varying(5) COLLATE pg_catalog."default",
    obs_ character varying(50) COLLATE pg_catalog."default",
    cod_n character varying(10) COLLATE pg_catalog."default",
    no_pl_gam character varying(12) COLLATE pg_catalog."default",
    no_matrc character varying(30) COLLATE pg_catalog."default",
    area_folio character varying(15) COLLATE pg_catalog."default",
    geom geometry(MultiPolygonZM,32719),
    via_id bigint,
    CONSTRAINT poligonos_pkey PRIMARY KEY (gid)
);

CREATE TABLE IF NOT EXISTS public.predios
(
    id bigserial NOT NULL,
    inmueble_padre_id bigint,
    propiedad_horizontal boolean NOT NULL DEFAULT false,
    numero_unidad character varying(20) COLLATE pg_catalog."default",
    codigo_catastral character varying(255) COLLATE pg_catalog."default" NOT NULL,
    numero_plano character varying(50) COLLATE pg_catalog."default",
    manzano character varying(20) COLLATE pg_catalog."default",
    lote character varying(20) COLLATE pg_catalog."default",
    zona character varying(255) COLLATE pg_catalog."default",
    sup_levantamiento double precision,
    sup_testimonio double precision,
    sup_construida double precision,
    sup_afectada double precision,
    sup_util double precision,
    coordenadas geometry(MultiPolygonZM,32719),
    frente_principal double precision,
    agua_potable boolean NOT NULL DEFAULT false,
    energia_electrica boolean NOT NULL DEFAULT false,
    alcantarillado boolean NOT NULL DEFAULT false,
    alumbrado_publico boolean NOT NULL DEFAULT false,
    gas_domiciliario boolean NOT NULL DEFAULT false,
    forma_lote boolean,
    fotografia_uno text COLLATE pg_catalog."default",
    fotografia_dos text COLLATE pg_catalog."default",
    fotografia_tres text COLLATE pg_catalog."default",
    fotografia_cuatro text COLLATE pg_catalog."default",
    fotografia_cinco text COLLATE pg_catalog."default",
    colindante_norte character varying(255) COLLATE pg_catalog."default",
    colindante_sur character varying(255) COLLATE pg_catalog."default",
    colindante_este character varying(255) COLLATE pg_catalog."default",
    colindante_oeste character varying(255) COLLATE pg_catalog."default",
    planimetria_id bigint NOT NULL,
    municipio_id bigint NOT NULL,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    deleted_at timestamp(0) without time zone,
    numero_matricula_folio character varying(255) COLLATE pg_catalog."default" NOT NULL,
    id_material_via bigint,
    via_id bigint,
    plano_aprobado boolean NOT NULL DEFAULT false,
    provincia_id bigint,
    centro_poblado_id bigint,
    CONSTRAINT predios_pkey PRIMARY KEY (id),
    CONSTRAINT predios_codigo_catastral_unique UNIQUE (codigo_catastral)
);

CREATE TABLE IF NOT EXISTS public.propietarios
(
    id bigserial NOT NULL,
    persona_id bigint NOT NULL,
    municipio_id bigint NOT NULL,
    estado boolean NOT NULL DEFAULT true,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    CONSTRAINT propietarios_pkey PRIMARY KEY (id),
    CONSTRAINT propietarios_persona_id_municipio_id_unique UNIQUE (persona_id, municipio_id)
);

CREATE TABLE IF NOT EXISTS public.propietarios_consolidados
(
    codigo character varying(10) COLLATE pg_catalog."default",
    propietario text COLLATE pg_catalog."default",
    ci_numero text COLLATE pg_catalog."default",
    expedicion text COLLATE pg_catalog."default"
);

CREATE TABLE IF NOT EXISTS public.propietarios_final
(
    codigo character varying(10) COLLATE pg_catalog."default",
    ci_numero text COLLATE pg_catalog."default",
    expedicion text COLLATE pg_catalog."default",
    nombre text COLLATE pg_catalog."default",
    primer_apellido text COLLATE pg_catalog."default",
    segundo_apellido text COLLATE pg_catalog."default"
);

CREATE TABLE IF NOT EXISTS public.propietarios_predios
(
    id bigserial NOT NULL,
    propietario_id bigint NOT NULL,
    predio_id bigint NOT NULL,
    estado character varying(255) COLLATE pg_catalog."default" NOT NULL,
    fecha_inicio date,
    fecha_fin date,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    CONSTRAINT propietarios_predios_pkey PRIMARY KEY (id),
    CONSTRAINT propietarios_predios_propietario_id_predio_id_estado_unique UNIQUE (propietario_id, predio_id, estado)
);

COMMENT ON COLUMN public.propietarios_predios.estado
    IS 'Ej: Propietario Actual, Ex-propietario';

CREATE TABLE IF NOT EXISTS public.provincias
(
    id bigserial NOT NULL,
    nombre character varying(255) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    deleted_at timestamp(0) without time zone,
    CONSTRAINT provincias_pkey PRIMARY KEY (id),
    CONSTRAINT provincias_nombre_unique UNIQUE (nombre)
);

CREATE TABLE IF NOT EXISTS public.requisitos
(
    id bigserial NOT NULL,
    nombre character varying(255) COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default",
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    CONSTRAINT requisitos_pkey PRIMARY KEY (id),
    CONSTRAINT requisitos_nombre_unique UNIQUE (nombre)
);

CREATE TABLE IF NOT EXISTS public.role_has_permissions
(
    permission_id bigint NOT NULL,
    role_id bigint NOT NULL,
    CONSTRAINT role_has_permissions_pkey PRIMARY KEY (permission_id, role_id)
);

CREATE TABLE IF NOT EXISTS public.roles
(
    id bigserial NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    guard_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    CONSTRAINT roles_pkey PRIMARY KEY (id),
    CONSTRAINT roles_name_guard_name_unique UNIQUE (name, guard_name)
);

CREATE TABLE IF NOT EXISTS public.sessions
(
    id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    user_id bigint,
    ip_address character varying(45) COLLATE pg_catalog."default",
    user_agent text COLLATE pg_catalog."default",
    payload text COLLATE pg_catalog."default" NOT NULL,
    last_activity integer NOT NULL,
    CONSTRAINT sessions_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tramite_documentos
(
    id bigserial NOT NULL,
    tramite_id bigint NOT NULL,
    requisito_id bigint NOT NULL,
    estado_id bigint NOT NULL,
    ruta_archivo text COLLATE pg_catalog."default" NOT NULL,
    nombre_original character varying(255) COLLATE pg_catalog."default" NOT NULL,
    observaciones text COLLATE pg_catalog."default",
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    user_id bigint,
    CONSTRAINT tramite_documentos_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tramite_estados
(
    id bigserial NOT NULL,
    nombre character varying(255) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    CONSTRAINT tramite_estados_pkey PRIMARY KEY (id),
    CONSTRAINT tramite_estados_nombre_unique UNIQUE (nombre)
);

CREATE TABLE IF NOT EXISTS public.tramite_tipo_requisitos
(
    tramite_tipo_id bigint NOT NULL,
    requisito_id bigint NOT NULL,
    CONSTRAINT tramite_tipo_requisitos_pkey PRIMARY KEY (tramite_tipo_id, requisito_id)
);

CREATE TABLE IF NOT EXISTS public.tramite_tipos
(
    id bigserial NOT NULL,
    nombre character varying(255) COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default",
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    CONSTRAINT tramite_tipos_pkey PRIMARY KEY (id),
    CONSTRAINT tramite_tipos_nombre_unique UNIQUE (nombre)
);

CREATE TABLE IF NOT EXISTS public.tramites
(
    id bigserial NOT NULL,
    predio_id bigint NOT NULL,
    municipio_id bigint NOT NULL,
    usuario_id bigint NOT NULL,
    solicitante_id bigint NOT NULL,
    tramite_tipo_id bigint NOT NULL,
    estado_id bigint NOT NULL,
    hoja_ruta character varying(255) COLLATE pg_catalog."default",
    fecha_ingreso date NOT NULL,
    fecha_inspeccion date,
    fecha_conclusion date,
    observaciones text COLLATE pg_catalog."default",
    fecha_paralizado date,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    deleted_at timestamp(0) without time zone,
    codigo_acceso character varying(8) COLLATE pg_catalog."default",
    ruta_certificado character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT tramites_pkey PRIMARY KEY (id),
    CONSTRAINT tramites_codigo_acceso_unique UNIQUE (codigo_acceso)
);

COMMENT ON COLUMN public.tramites.usuario_id
    IS 'Usuario del sistema que registra el trÃ¡mite';

COMMENT ON COLUMN public.tramites.solicitante_id
    IS 'Persona (propietario o apoderado) que inicia el trÃ¡mite';

COMMENT ON COLUMN public.tramites.fecha_paralizado
    IS 'Fecha en que el trÃ¡mite pasa a "Paralizado" para el contador de 10 dÃ­as.';

COMMENT ON COLUMN public.tramites.codigo_acceso
    IS 'CÃ³digo secreto para la consulta pÃºblica del solicitante.';

CREATE TABLE IF NOT EXISTS public.users
(
    id bigserial NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    email_verified_at timestamp(0) without time zone,
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    remember_token character varying(100) COLLATE pg_catalog."default",
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    deleted_at timestamp(0) without time zone,
    municipio_id bigint,
    persona_id bigint NOT NULL,
    google2fa_secret text COLLATE pg_catalog."default",
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_unique UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.vias
(
    id bigserial NOT NULL,
    nombre character varying(255) COLLATE pg_catalog."default" NOT NULL,
    municipio_id bigint NOT NULL,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    CONSTRAINT vias_pkey PRIMARY KEY (id),
    CONSTRAINT vias_nombre_municipio_id_unique UNIQUE (nombre, municipio_id)
);

ALTER TABLE IF EXISTS public.asignaciones
    ADD CONSTRAINT asignaciones_municipio_id_foreign FOREIGN KEY (municipio_id)
    REFERENCES public.municipios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.asignaciones
    ADD CONSTRAINT asignaciones_user_id_foreign FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.model_has_permissions
    ADD CONSTRAINT model_has_permissions_permission_id_foreign FOREIGN KEY (permission_id)
    REFERENCES public.permissions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.model_has_roles
    ADD CONSTRAINT model_has_roles_role_id_foreign FOREIGN KEY (role_id)
    REFERENCES public.roles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.planimetrias
    ADD CONSTRAINT planimetrias_municipio_id_foreign FOREIGN KEY (municipio_id)
    REFERENCES public.municipios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.predios
    ADD CONSTRAINT predios_centro_poblado_id_foreign FOREIGN KEY (centro_poblado_id)
    REFERENCES public.centro_poblados (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.predios
    ADD CONSTRAINT predios_id_material_via_foreign FOREIGN KEY (id_material_via)
    REFERENCES public.materiales_via (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.predios
    ADD CONSTRAINT predios_inmueble_padre_id_foreign FOREIGN KEY (inmueble_padre_id)
    REFERENCES public.predios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.predios
    ADD CONSTRAINT predios_municipio_id_foreign FOREIGN KEY (municipio_id)
    REFERENCES public.municipios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.predios
    ADD CONSTRAINT predios_planimetria_id_foreign FOREIGN KEY (planimetria_id)
    REFERENCES public.planimetrias (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.predios
    ADD CONSTRAINT predios_provincia_id_foreign FOREIGN KEY (provincia_id)
    REFERENCES public.provincias (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.predios
    ADD CONSTRAINT predios_via_id_foreign FOREIGN KEY (via_id)
    REFERENCES public.vias (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.propietarios
    ADD CONSTRAINT propietarios_municipio_id_foreign FOREIGN KEY (municipio_id)
    REFERENCES public.municipios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.propietarios
    ADD CONSTRAINT propietarios_persona_id_foreign FOREIGN KEY (persona_id)
    REFERENCES public.personas (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.propietarios_predios
    ADD CONSTRAINT propietarios_predios_predio_id_foreign FOREIGN KEY (predio_id)
    REFERENCES public.predios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.propietarios_predios
    ADD CONSTRAINT propietarios_predios_propietario_id_foreign FOREIGN KEY (propietario_id)
    REFERENCES public.propietarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.role_has_permissions
    ADD CONSTRAINT role_has_permissions_permission_id_foreign FOREIGN KEY (permission_id)
    REFERENCES public.permissions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.role_has_permissions
    ADD CONSTRAINT role_has_permissions_role_id_foreign FOREIGN KEY (role_id)
    REFERENCES public.roles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.tramite_documentos
    ADD CONSTRAINT tramite_documentos_estado_id_foreign FOREIGN KEY (estado_id)
    REFERENCES public.documento_estados (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.tramite_documentos
    ADD CONSTRAINT tramite_documentos_requisito_id_foreign FOREIGN KEY (requisito_id)
    REFERENCES public.requisitos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.tramite_documentos
    ADD CONSTRAINT tramite_documentos_tramite_id_foreign FOREIGN KEY (tramite_id)
    REFERENCES public.tramites (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.tramite_documentos
    ADD CONSTRAINT tramite_documentos_user_id_foreign FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.tramite_tipo_requisitos
    ADD CONSTRAINT tramite_tipo_requisitos_requisito_id_foreign FOREIGN KEY (requisito_id)
    REFERENCES public.requisitos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.tramite_tipo_requisitos
    ADD CONSTRAINT tramite_tipo_requisitos_tramite_tipo_id_foreign FOREIGN KEY (tramite_tipo_id)
    REFERENCES public.tramite_tipos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.tramites
    ADD CONSTRAINT tramites_estado_id_foreign FOREIGN KEY (estado_id)
    REFERENCES public.tramite_estados (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.tramites
    ADD CONSTRAINT tramites_municipio_id_foreign FOREIGN KEY (municipio_id)
    REFERENCES public.municipios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.tramites
    ADD CONSTRAINT tramites_predio_id_foreign FOREIGN KEY (predio_id)
    REFERENCES public.predios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.tramites
    ADD CONSTRAINT tramites_solicitante_id_foreign FOREIGN KEY (solicitante_id)
    REFERENCES public.personas (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.tramites
    ADD CONSTRAINT tramites_tramite_tipo_id_foreign FOREIGN KEY (tramite_tipo_id)
    REFERENCES public.tramite_tipos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.tramites
    ADD CONSTRAINT tramites_usuario_id_foreign FOREIGN KEY (usuario_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.users
    ADD CONSTRAINT users_municipio_id_foreign FOREIGN KEY (municipio_id)
    REFERENCES public.municipios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.users
    ADD CONSTRAINT users_persona_id_foreign FOREIGN KEY (persona_id)
    REFERENCES public.personas (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.vias
    ADD CONSTRAINT vias_municipio_id_foreign FOREIGN KEY (municipio_id)
    REFERENCES public.municipios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

END;